[package]
name = "bytestring"
version = "0.1.0"
authors = ["pluth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
serde = {version = "1", optional = true}

[features]